### ISSUE TITLE
Custom templates missing after upgrade to 1.1.0

### ISSUE THREAD

**Issue by liquidsunshine** [adamtootle/staff-directory#14]
Our site broke after updating the staff-directory plugin to 1.1.0.  I did the following to restore our site: 
- backed up a copy of the staff-directory plugin folder
- deleted the plugin folder
- logged into the site
- installed 1.0.3 from the Github tag

This got our site back up and running, but all of our custom directory list templates seem to be gone.  I upgraded to PHP7 per issue #13 and upgraded the plugin to 1.1.0 again, but they are still missing.

Where should these custom templates be "stored" (e.g. database table, folder, etc.) and is there a non-catastrophic reason they wouldn't be showing up?

**Comment by TurqDevDesign** [comment]
Hi, @liquidsunshine, I apologize for the issues. Unfortunately what you're experiencing was a bug with 1.0.3, fixed in 1.1.0. In 1.0.3 when you deactivated the plugin, or when your cache was wiped, Wordpress would unintentionally overwrite the templates. If you happen to have a backup of your database then you should be able to fix the issue. The Custom templates are stored, escaped and, in 1.1.0, special characters converted to HTML entities in *_options > staff_directory_custom_templates. Copying that field from a 1.0.3 installation to 1.1.0 should restore your custom templates. 

**NOTE:** *After doing this, I would suggest going back in to your Staff Directory settings and simply re-saving, this will update your templates, properly encoding the special characters, preventing the same issue in the future.* 

As well, we did a lot of debugging from issue #13 yesterday, if you manually update your plugin from the github repo, it should help to avoid the other issues you've been facing. I believe that @adamtootle has pushed the patches to the Wordpress SVN, but I'm not sure how long those will take to clear.

**Comment by liquidsunshine** [comment]
Thanks for the explanation.  We recreated the templates and upgraded to 1.1.1, everything looks good now.  Thanks again!
