### ISSUE TITLE
Multiple category ids for [staff-directory] shortcode

### ISSUE THREAD

**Issue by delitestudio** [adamtootle/staff-directory#3]
We have implemented the feature and we have allowed the shortcode to use slugs instead of ids.
If you want we can submit a pull request to your GitHub repository.
We think supporting slug and multiple categories may be a pro for everyone.

**Comment by adamtootle** [comment]
@delitestudio are you still interested in a PR for this? It'll need to be on top of the 1.0.3 release since a lot of code formatting has been updated. If not I can probably knock this out on my end.

**Comment by delitestudio** [comment]
We will try it in spare time, but we cannot assure it will work as we have implemented it an year ago.

**Comment by adamtootle** [comment]
@delitestudio totally understandable. I'll leave this here for now. Feel free to close if you'd like. Otherwise I may try to add support on my end at some point and reference it here.

**Comment by delitestudio** [comment]
@adamtootle we have made the pull request #10

**Comment by adamtootle** [comment]
@delitestudio just a heads up. Defaulting to AND logic for multiple categories was causing some issues (see #10). The shortcode now support the following options for categories: `cat` (accepts multiple IDS or slugs), `cat_field` (defaults to 'ID', can be set to 'slug'), and `cat_relation` (defaults to 'OR' but can be set to 'AND'). I just wanted to let you guys know since you added some stuff for querying multiple slugs and that syntax has changed slightly in v1.1.1.

**Comment by delitestudio** [comment]
Thank you @adamtootle we have upgraded our sites with the new options and they are working greatly! Sorry for any inconvenience the forced "AND" logic may have caused.
